export {
  browserCaptureDescriptor,
  browserCaptureClearCropScope,
  browserCaptureGetPreviewScope,
  browserCaptureInspectTargetsScope,
  browserCaptureSetCaptureFpsScope,
  browserCaptureSetCropScope,
  browserCaptureSetTargetScope,
  browserPreviewTargetsArtifactKind,
  createBrowserCaptureDriver,
  makeBrowserPageCaptureAdapter,
  makeBrowserPageFactoryCaptureAdapter,
  validateBrowserCaptureConfig,
  validateBrowserCapturePageReadiness,
  validateCaptureFps,
  validateCrop,
  validateEncoding,
  validateViewport
} from "./driver.js";

export type {
  BrowserCaptureAdapter,
  BrowserCaptureBridgeError,
  BrowserCaptureConfig,
  BrowserCaptureControls,
  BrowserCaptureCrop,
  BrowserCaptureImageEncoding,
  BrowserCaptureOpenOptions,
  BrowserCapturePage,
  BrowserCapturePageReadiness,
  BrowserCapturePreview,
  BrowserCaptureReadinessError,
  BrowserCaptureRuntimeConfigSnapshot,
  BrowserCaptureScreenshot,
  BrowserCaptureScreenshotOptions,
  BrowserCaptureSetCaptureFpsPayload,
  BrowserCaptureSetCropPayload,
  BrowserCaptureSetTargetPayload,
  BrowserCaptureTarget,
  BrowserCaptureTargetInspection,
  BrowserCaptureViewport,
  BrowserPageCaptureAdapterKind,
  BrowserPageCaptureAdapterOptions,
  BrowserPageCaptureFactory,
  BrowserPreviewTargetsArtifactPayload,
  ResolvedBrowserPageCaptureAdapterKind
} from "./driver.js";
