// Auto-generated by deploy:sui — do not edit by hand.
// Re-run `npm run deploy:sui` to regenerate from the latest localnet deployment.
import type { SuiDeployment } from "../types.js";

export const localnetDeployment: SuiDeployment = {
  chain: "localnet",
  rpc: "http://127.0.0.1:9000",
  deployedAt: "2026-07-18T19:48:31.321Z",
  deployer: "0x668cfc490bd30cf8d4666e3ff39cc7fded31deee89d105267011d01abea94e84",
  packageId: "0x2dd6ba243b58ac19ce8b379d4849038f688412a2097f5b798af816c57c03b019",
  objects: {
    packageId: "0x2dd6ba243b58ac19ce8b379d4849038f688412a2097f5b798af816c57c03b019",
    protocol: "0xb8806f95d9420c8e29d3f8bc267371041cd4709ae8be3df68691ba521916269b",
    marketRegistry: "0x6ec9f7083410176e325619bbf99a74052d4764f9d04ce53d9ca0c21dd78b9b5f",
    vaultRegistry: "0x0c9a58dae0b1073ac57255553768cafa1956e20eab3344c6f78134bcccc500eb",
    stewardRegistry: "0x9a58d76d4ac20be3638763168582ee5a3b34688c60f4648dad4531ee1ba41bc2",
    treasuryRegistry: "0x72dc18a140518bd1257494827575db8238cf8aac4967a736f94fb2df8b57bf8d",
    dripsRegistry: "0x793862b757b3d42eb608c6c99b6b977cdcb4449647f1a3d3d9bd3f455f421b58",
    streamsRegistry: "0x05b41ba9bc55946da580912c8b5593b6d632feede5e22c3af31a705e3592f1a2",
    vaultDriverRegistry: "0x037a1444596a83bb125b02c6c37e354d63e88a5cd48e4c171df7d85a31c62dec",
    marketDriverRegistry: "0x7fcda45cf8bfaee8d67367627702ff41a9fe08a9728a064d087eba2fc1828d3e",
    driverRegistry: "0x340ab7ffe55eacd091f88f674a11d1894d2daa4956eb7400da355d10e10fed58",
    lvstTreasuryCap: "0x875af2c8ee9c82b5dd930557f4e31fbaaa1d3e0fd23a48a84d2ed55237d85c4c",
    usdcMintCap: "0x5728e0da4a6f5cc6c06633cb85526a8df26ea05c095062f423cbd1ad02d7041d",
  },
};
