import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { SolanaDeployment, SolanaDeploymentName } from "../types.js";

const here = dirname(fileURLToPath(import.meta.url));
export const SOLANA_ROOT = join(here, "..");
export const DEPLOYMENTS_DIR = join(SOLANA_ROOT, "deployments");
export const PROGRAM_DIR = join(SOLANA_ROOT, "program");

export function writeDeployment(name: SolanaDeploymentName, snapshot: SolanaDeployment): void {
  mkdirSync(DEPLOYMENTS_DIR, { recursive: true });
  writeFileSync(join(DEPLOYMENTS_DIR, `${name}.json`), JSON.stringify(snapshot, null, 2));
  writeDeploymentTs(name, snapshot);
}

/** Write a browser-safe typed TypeScript const alongside the JSON snapshot. */
export function writeDeploymentTs(name: SolanaDeploymentName, snapshot: SolanaDeployment): void {
  const varName = `${name}Deployment`;
  const accountLines = Object.entries(snapshot.accounts)
    .map(([k, v]) => `    ${k}: "${v}",`)
    .join("\n");
  const ts = [
    `// Auto-generated by deploy:solana — do not edit by hand.`,
    `// Re-run \`npm run deploy:solana\` to regenerate from the latest ${name} deployment.`,
    `import type { SolanaDeployment } from "../types.js";`,
    ``,
    `export const ${varName}: SolanaDeployment = {`,
    `  chain: "${snapshot.chain}",`,
    `  rpc: "${snapshot.rpc}",`,
    `  deployedAt: "${snapshot.deployedAt}",`,
    `  deployer: "${snapshot.deployer}",`,
    `  programId: "${snapshot.programId}",`,
    `  accounts: {`,
    accountLines,
    `  },`,
    `};`,
    ``,
  ].join("\n");
  writeFileSync(join(DEPLOYMENTS_DIR, `${name}.ts`), ts);
}
