// Auto-generated by sync-idl.mjs from program/target/idl — do not edit by hand.
// Re-run `npm run build:solana:idl` after `anchor build` to refresh.
import type { Livestreak } from "./livestreak-types.js";

export const livestreakIdl = {
  "address": "CZnAfgbnbVtuXDRQynwL9XMHqeQ7wngbodRihGLbErK8",
  "metadata": {
    "name": "livestreak",
    "version": "0.1.0",
    "spec": "0.1.0",
    "description": "LiveStreak protocol — Solana port (ported from the Sui Move sources)"
  },
  "instructions": [
    {
      "name": "advance",
      "discriminator": [
        7,
        56,
        108,
        201,
        36,
        20,
        57,
        89
      ],
      "accounts": [
        {
          "name": "protocol_state",
          "writable": true
        },
        {
          "name": "escrow",
          "docs": [
            "Read-only: present so the conservation guard can verify the invariant."
          ]
        }
      ],
      "args": [
        {
          "name": "vault_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        },
        {
          "name": "side",
          "type": "u8"
        },
        {
          "name": "max_steps",
          "type": "u64"
        }
      ]
    },
    {
      "name": "claim_dividends",
      "discriminator": [
        105,
        60,
        172,
        2,
        136,
        93,
        128,
        151
      ],
      "accounts": [
        {
          "name": "staker",
          "signer": true
        },
        {
          "name": "protocol_state",
          "writable": true
        },
        {
          "name": "escrow",
          "writable": true
        },
        {
          "name": "staker_usdc",
          "docs": [
            "The staker's USDC token account. Require-exists (mirrors the other user_usdc ATAs)."
          ],
          "writable": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": []
    },
    {
      "name": "claim_loss_lvst",
      "discriminator": [
        106,
        174,
        157,
        64,
        132,
        175,
        142,
        147
      ],
      "accounts": [
        {
          "name": "claimer",
          "signer": true
        },
        {
          "name": "protocol_state",
          "writable": true
        },
        {
          "name": "position",
          "docs": [
            "Ownership gate: the claimer must own the position whose token_id fixes the loss."
          ]
        },
        {
          "name": "lvst_authority",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  118,
                  115,
                  116,
                  95,
                  97,
                  117,
                  116,
                  104,
                  111,
                  114,
                  105,
                  116,
                  121
                ]
              }
            ]
          }
        },
        {
          "name": "lvst_mint",
          "docs": [
            "The canonical LVST mint (its authority must be the lvst_authority PDA)."
          ],
          "writable": true
        },
        {
          "name": "claimer_lvst",
          "docs": [
            "The claimer's LVST token account. Require-exists (mirrors how the program treats",
            "user USDC ATAs): the client prepends a createAtaIdempotent for the LVST mint."
          ],
          "writable": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "vault_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        },
        {
          "name": "side",
          "type": "u8"
        }
      ]
    },
    {
      "name": "collect",
      "discriminator": [
        208,
        47,
        194,
        155,
        17,
        98,
        82,
        236
      ],
      "accounts": [
        {
          "name": "protocol_state",
          "writable": true
        },
        {
          "name": "escrow",
          "docs": [
            "Read-only: present so the conservation guard can verify the invariant."
          ]
        }
      ],
      "args": [
        {
          "name": "vault_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "create_vault_seeded",
      "discriminator": [
        203,
        113,
        87,
        226,
        69,
        108,
        101,
        19
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "protocol_state",
          "writable": true
        },
        {
          "name": "escrow",
          "writable": true
        },
        {
          "name": "user_usdc",
          "writable": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "question",
          "type": "bytes"
        },
        {
          "name": "seed_side",
          "type": "u8"
        },
        {
          "name": "rate",
          "type": "u64"
        },
        {
          "name": "deposit",
          "type": "u64"
        }
      ],
      "returns": "bytes"
    },
    {
      "name": "fund",
      "discriminator": [
        218,
        188,
        111,
        221,
        152,
        113,
        174,
        7
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "protocol_state",
          "writable": true
        },
        {
          "name": "position"
        },
        {
          "name": "escrow",
          "writable": true
        },
        {
          "name": "user_usdc",
          "writable": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "vault_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        },
        {
          "name": "side",
          "type": "u8"
        },
        {
          "name": "rate",
          "type": "u64"
        },
        {
          "name": "deposit",
          "type": "u64"
        }
      ]
    },
    {
      "name": "go_live",
      "discriminator": [
        126,
        98,
        10,
        43,
        92,
        184,
        85,
        248
      ],
      "accounts": [
        {
          "name": "creator",
          "signer": true,
          "relations": [
            "market"
          ]
        },
        {
          "name": "market",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "scheme",
          "type": "u8"
        },
        {
          "name": "pointer",
          "type": "bytes"
        }
      ]
    },
    {
      "name": "init_protocol",
      "discriminator": [
        3,
        188,
        141,
        237,
        225,
        226,
        232,
        210
      ],
      "accounts": [
        {
          "name": "payer",
          "writable": true,
          "signer": true
        },
        {
          "name": "market"
        },
        {
          "name": "protocol_state",
          "writable": true
        },
        {
          "name": "usdc_mint"
        },
        {
          "name": "escrow",
          "writable": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "capacity",
          "type": "u16"
        }
      ]
    },
    {
      "name": "initialize",
      "discriminator": [
        175,
        175,
        109,
        31,
        13,
        152,
        155,
        237
      ],
      "accounts": [
        {
          "name": "payer",
          "writable": true,
          "signer": true
        },
        {
          "name": "registry",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  101,
                  103,
                  105,
                  115,
                  116,
                  114,
                  121
                ]
              }
            ]
          }
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "default_steward",
          "type": "pubkey"
        },
        {
          "name": "lvst_mint",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "mint_position",
      "discriminator": [
        251,
        31,
        179,
        3,
        138,
        134,
        203,
        28
      ],
      "accounts": [
        {
          "name": "minter",
          "writable": true,
          "signer": true
        },
        {
          "name": "protocol_state",
          "writable": true
        },
        {
          "name": "market"
        },
        {
          "name": "position",
          "writable": true
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "salt",
          "type": "u64"
        }
      ]
    },
    {
      "name": "register_market",
      "discriminator": [
        24,
        163,
        183,
        185,
        145,
        243,
        36,
        146
      ],
      "accounts": [
        {
          "name": "creator",
          "writable": true,
          "signer": true
        },
        {
          "name": "registry",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  101,
                  103,
                  105,
                  115,
                  116,
                  114,
                  121
                ]
              }
            ]
          }
        },
        {
          "name": "market",
          "writable": true
        },
        {
          "name": "market_index",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116,
                  95,
                  105,
                  100,
                  120
                ]
              },
              {
                "kind": "account",
                "path": "registry.market_count",
                "account": "Registry"
              }
            ]
          }
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "title",
          "type": "bytes"
        },
        {
          "name": "stream_id",
          "type": "bytes"
        }
      ]
    },
    {
      "name": "resolve",
      "discriminator": [
        246,
        150,
        236,
        206,
        108,
        63,
        58,
        10
      ],
      "accounts": [
        {
          "name": "steward",
          "signer": true
        },
        {
          "name": "protocol_state",
          "writable": true
        },
        {
          "name": "registry",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  101,
                  103,
                  105,
                  115,
                  116,
                  114,
                  121
                ]
              }
            ]
          }
        },
        {
          "name": "market_steward",
          "docs": [
            "Per-market override; pass the registry's default when none exists."
          ],
          "optional": true
        }
      ],
      "args": [
        {
          "name": "vault_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        },
        {
          "name": "winning_side",
          "type": "u8"
        }
      ]
    },
    {
      "name": "set_default_steward",
      "discriminator": [
        147,
        90,
        32,
        234,
        146,
        51,
        12,
        85
      ],
      "accounts": [
        {
          "name": "authority",
          "signer": true
        },
        {
          "name": "registry",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  101,
                  103,
                  105,
                  115,
                  116,
                  114,
                  121
                ]
              }
            ]
          }
        }
      ],
      "args": [
        {
          "name": "steward",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "set_ended",
      "discriminator": [
        138,
        92,
        84,
        48,
        74,
        233,
        182,
        216
      ],
      "accounts": [
        {
          "name": "creator",
          "signer": true,
          "relations": [
            "market"
          ]
        },
        {
          "name": "market",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "scheme",
          "type": "u8"
        },
        {
          "name": "pointer",
          "type": "bytes"
        }
      ]
    },
    {
      "name": "set_lanes",
      "discriminator": [
        199,
        5,
        232,
        61,
        20,
        92,
        40,
        134
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "protocol_state",
          "writable": true
        },
        {
          "name": "position"
        },
        {
          "name": "escrow",
          "writable": true
        },
        {
          "name": "user_usdc",
          "writable": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "lanes",
          "type": {
            "vec": {
              "defined": {
                "name": "LaneArg"
              }
            }
          }
        },
        {
          "name": "add_deposit",
          "type": "u64"
        }
      ]
    },
    {
      "name": "set_market_steward",
      "discriminator": [
        124,
        136,
        234,
        202,
        9,
        248,
        242,
        31
      ],
      "accounts": [
        {
          "name": "authority",
          "writable": true,
          "signer": true
        },
        {
          "name": "registry",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  101,
                  103,
                  105,
                  115,
                  116,
                  114,
                  121
                ]
              }
            ]
          }
        },
        {
          "name": "market"
        },
        {
          "name": "market_steward",
          "writable": true
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "steward",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "stake_lvst",
      "discriminator": [
        129,
        163,
        230,
        235,
        42,
        158,
        89,
        219
      ],
      "accounts": [
        {
          "name": "staker",
          "writable": true,
          "signer": true
        },
        {
          "name": "protocol_state",
          "writable": true
        },
        {
          "name": "registry",
          "docs": [
            "Read-only registry: the canonical LVST mint lives here (recorded at initialize)."
          ],
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  101,
                  103,
                  105,
                  115,
                  116,
                  114,
                  121
                ]
              }
            ]
          }
        },
        {
          "name": "lvst_mint"
        },
        {
          "name": "lvst_escrow",
          "docs": [
            "Per-market LVST staking escrow, created lazily on the first stake (payer = staker).",
            "init_if_needed is already an enabled anchor feature; a lazy init keeps this to the",
            "scoped two instructions (no separate init op / extra client round-trip) and cannot",
            "be griefed into a bad state — the seeds are fixed and the mint/authority constraints",
            "are re-checked on every call, so there is no trusted data to corrupt."
          ],
          "writable": true
        },
        {
          "name": "staker_lvst",
          "writable": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "stop_all",
      "discriminator": [
        192,
        239,
        176,
        82,
        185,
        47,
        125,
        214
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "protocol_state",
          "writable": true
        },
        {
          "name": "position"
        },
        {
          "name": "escrow",
          "writable": true
        },
        {
          "name": "user_usdc",
          "writable": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": []
    },
    {
      "name": "stop_funding",
      "discriminator": [
        67,
        127,
        232,
        106,
        65,
        131,
        19,
        218
      ],
      "accounts": [
        {
          "name": "user",
          "signer": true
        },
        {
          "name": "protocol_state",
          "writable": true
        },
        {
          "name": "position"
        }
      ],
      "args": [
        {
          "name": "vault_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        },
        {
          "name": "side",
          "type": "u8"
        }
      ]
    },
    {
      "name": "stop_seed",
      "discriminator": [
        194,
        156,
        255,
        171,
        197,
        193,
        16,
        245
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "protocol_state",
          "writable": true
        },
        {
          "name": "escrow",
          "writable": true
        },
        {
          "name": "user_usdc",
          "writable": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "vault_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "transfer_position",
      "discriminator": [
        139,
        130,
        102,
        147,
        135,
        77,
        113,
        222
      ],
      "accounts": [
        {
          "name": "owner",
          "signer": true
        },
        {
          "name": "position",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "new_owner",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "unstake_lvst",
      "discriminator": [
        145,
        44,
        251,
        143,
        99,
        253,
        94,
        26
      ],
      "accounts": [
        {
          "name": "staker",
          "signer": true
        },
        {
          "name": "protocol_state",
          "writable": true
        },
        {
          "name": "lvst_mint"
        },
        {
          "name": "lvst_escrow",
          "docs": [
            "Require-exists: you cannot unstake without a prior stake, which created this escrow."
          ],
          "writable": true
        },
        {
          "name": "staker_lvst",
          "writable": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "withdraw",
      "discriminator": [
        183,
        18,
        70,
        156,
        148,
        109,
        161,
        34
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "protocol_state",
          "writable": true
        },
        {
          "name": "position"
        },
        {
          "name": "escrow",
          "writable": true
        },
        {
          "name": "user_usdc",
          "writable": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "vault_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "withdraw_seed",
      "discriminator": [
        6,
        229,
        202,
        82,
        245,
        58,
        212,
        125
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "protocol_state",
          "writable": true
        },
        {
          "name": "escrow",
          "writable": true
        },
        {
          "name": "user_usdc",
          "writable": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "vault_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    }
  ],
  "accounts": [
    {
      "name": "Market",
      "discriminator": [
        219,
        190,
        213,
        55,
        0,
        227,
        198,
        154
      ]
    },
    {
      "name": "MarketIndex",
      "discriminator": [
        82,
        184,
        235,
        96,
        200,
        193,
        242,
        21
      ]
    },
    {
      "name": "MarketSteward",
      "discriminator": [
        183,
        148,
        185,
        192,
        99,
        97,
        65,
        169
      ]
    },
    {
      "name": "PositionOwner",
      "discriminator": [
        178,
        102,
        135,
        78,
        61,
        157,
        171,
        203
      ]
    },
    {
      "name": "ProtocolState",
      "discriminator": [
        33,
        51,
        173,
        134,
        35,
        140,
        195,
        248
      ]
    },
    {
      "name": "Registry",
      "discriminator": [
        47,
        174,
        110,
        246,
        184,
        182,
        252,
        218
      ]
    }
  ],
  "errors": [
    {
      "code": 6000,
      "name": "EmptyTitle",
      "msg": "title must be non-empty"
    },
    {
      "code": 6001,
      "name": "ZeroStreamId",
      "msg": "stream id must be non-empty"
    },
    {
      "code": 6002,
      "name": "InputTooLong",
      "msg": "input exceeds maximum length"
    },
    {
      "code": 6003,
      "name": "NotCreator",
      "msg": "caller is not the market creator"
    },
    {
      "code": 6004,
      "name": "StreamEnded",
      "msg": "stream already ended"
    },
    {
      "code": 6005,
      "name": "NotLive",
      "msg": "stream was never live"
    },
    {
      "code": 6006,
      "name": "StreamLocked",
      "msg": "stream pointer is locked (evidence grace elapsed)"
    },
    {
      "code": 6007,
      "name": "BadScheme",
      "msg": "unknown storage pointer scheme"
    },
    {
      "code": 6008,
      "name": "EngineState",
      "msg": "protocol state failed to decode"
    },
    {
      "code": 6009,
      "name": "StateFull",
      "msg": "protocol state account is full"
    },
    {
      "code": 6010,
      "name": "EngineOp",
      "msg": "engine operation failed (see logs)"
    },
    {
      "code": 6011,
      "name": "NotSteward",
      "msg": "caller is not the effective steward"
    },
    {
      "code": 6012,
      "name": "ConservationViolated",
      "msg": "escrow balance diverged from engine ledgers"
    },
    {
      "code": 6013,
      "name": "SettlementPending",
      "msg": "settlement pending: winnings payable after the cycle boundary at ready_at"
    },
    {
      "code": 6014,
      "name": "WrongLvstMint",
      "msg": "staked mint is not the canonical LVST mint recorded in the registry"
    },
    {
      "code": 6015,
      "name": "NoDividends",
      "msg": "no dividends accrued to claim"
    },
    {
      "code": 6016,
      "name": "ZeroNewOwner",
      "msg": "new position owner must be non-zero"
    },
    {
      "code": 6017,
      "name": "StreamsTooManyReceivers",
      "msg": "too many stream receivers"
    },
    {
      "code": 6018,
      "name": "StreamsReceiversNotSorted",
      "msg": "stream receivers not sorted"
    },
    {
      "code": 6019,
      "name": "StreamsAmtPerSecTooLow",
      "msg": "stream rate below minimum"
    },
    {
      "code": 6020,
      "name": "StreamsCycleSecsTooLow",
      "msg": "cycle seconds below minimum"
    },
    {
      "code": 6021,
      "name": "StreamsInvalidReceivers",
      "msg": "invalid streams receivers"
    },
    {
      "code": 6022,
      "name": "StreamsInvalidHistory",
      "msg": "invalid streams history"
    },
    {
      "code": 6023,
      "name": "StreamsEntryWithHashAndReceivers",
      "msg": "history entry has both hash and receivers"
    },
    {
      "code": 6024,
      "name": "StreamsTimestampBeforeUpdate",
      "msg": "timestamp before last update"
    },
    {
      "code": 6025,
      "name": "StreamsBalanceTooHigh",
      "msg": "streams balance too high"
    },
    {
      "code": 6026,
      "name": "VaultEmptyQuestion",
      "msg": "vault question must be non-empty"
    },
    {
      "code": 6027,
      "name": "VaultZeroCreator",
      "msg": "vault creator must be non-zero"
    },
    {
      "code": 6028,
      "name": "VaultUnknown",
      "msg": "unknown vault"
    },
    {
      "code": 6029,
      "name": "VaultNotOpen",
      "msg": "vault is not open"
    },
    {
      "code": 6030,
      "name": "VaultZeroRate",
      "msg": "vault rate must be non-zero"
    },
    {
      "code": 6031,
      "name": "VaultAlreadyFunding",
      "msg": "position already funding this vault"
    },
    {
      "code": 6032,
      "name": "VaultLengthMismatch",
      "msg": "vault input length mismatch"
    },
    {
      "code": 6033,
      "name": "VaultNotResolvable",
      "msg": "vault is not resolvable"
    },
    {
      "code": 6034,
      "name": "VaultNotResolved",
      "msg": "vault is not resolved"
    },
    {
      "code": 6035,
      "name": "VaultBoardBehind",
      "msg": "board is behind; advance before settling"
    },
    {
      "code": 6036,
      "name": "VaultDivZero",
      "msg": "division by zero in vault math"
    },
    {
      "code": 6037,
      "name": "VaultInsufficientUsdc",
      "msg": "insufficient USDC in vault ledger"
    },
    {
      "code": 6038,
      "name": "DriverSaltUsed",
      "msg": "mint salt already used"
    },
    {
      "code": 6039,
      "name": "DriverUnknownMarket",
      "msg": "unknown market"
    },
    {
      "code": 6040,
      "name": "DriverZeroRate",
      "msg": "lane rate must be non-zero"
    },
    {
      "code": 6041,
      "name": "DriverBadDeposit",
      "msg": "bad deposit amount"
    },
    {
      "code": 6042,
      "name": "DriverWrongMarket",
      "msg": "vault belongs to a different market"
    },
    {
      "code": 6043,
      "name": "DriverVaultHasLane",
      "msg": "position already has a lane on this vault"
    },
    {
      "code": 6044,
      "name": "DriverTooManyLanes",
      "msg": "too many lanes on this position"
    },
    {
      "code": 6045,
      "name": "DriverNoLane",
      "msg": "no lane on this vault"
    },
    {
      "code": 6046,
      "name": "DriverDuplicateVault",
      "msg": "duplicate vault in lane set"
    },
    {
      "code": 6047,
      "name": "DriverLengthMismatch",
      "msg": "driver input length mismatch"
    },
    {
      "code": 6048,
      "name": "DriverSeedExists",
      "msg": "seed lane already exists"
    },
    {
      "code": 6049,
      "name": "DriverNoSeed",
      "msg": "no seed lane"
    },
    {
      "code": 6050,
      "name": "DripsTotalBalanceTooHigh",
      "msg": "total streamed balance too high"
    },
    {
      "code": 6051,
      "name": "DripsTokenBalanceTooLow",
      "msg": "token balance too low"
    },
    {
      "code": 6052,
      "name": "DripsWithdrawalAmountTooHigh",
      "msg": "withdrawal amount too high"
    },
    {
      "code": 6053,
      "name": "TreasuryAlreadyClaimed",
      "msg": "loss already claimed"
    },
    {
      "code": 6054,
      "name": "TreasuryNothingLost",
      "msg": "nothing lost to claim"
    },
    {
      "code": 6055,
      "name": "TreasuryZeroStake",
      "msg": "stake must be non-zero"
    },
    {
      "code": 6056,
      "name": "TreasuryInvalidUnstake",
      "msg": "invalid unstake amount"
    }
  ],
  "types": [
    {
      "name": "LaneArg",
      "docs": [
        "One desired lane in a `set_lanes` full-set declaration. Rates are the human u64 the",
        "client speaks (mirroring `fund`); the handler widens each to the engine's U256 before",
        "the driver call. Anchor-(de)serializable so it rides in the `Vec<LaneArg>` arg."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "vault_id",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "side",
            "type": "u8"
          },
          {
            "name": "rate",
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "Market",
      "docs": [
        "One market. PDA: [\"market\", market_id]. market_id = keccak256(creator ++ stream_id),",
        "the same id scheme as Move compute_market_id — 32 opaque bytes on every chain."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market_id",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "creator",
            "type": "pubkey"
          },
          {
            "name": "title",
            "type": "bytes"
          },
          {
            "name": "stream_id",
            "type": "bytes"
          },
          {
            "name": "created_at",
            "type": "i64"
          },
          {
            "name": "stream_status",
            "type": "u8"
          },
          {
            "name": "stream_scheme",
            "type": "u8"
          },
          {
            "name": "stream_pointer",
            "type": "bytes"
          },
          {
            "name": "stream_updated_at",
            "type": "i64"
          },
          {
            "name": "stream_ended_at",
            "type": "i64"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "MarketIndex",
      "docs": [
        "Enumeration ledger: PDA [\"market_idx\", index_le] -> market_id.",
        "The append-only equivalent of EVM marketIdAt / Move market_ids."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market_id",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "MarketSteward",
      "docs": [
        "Per-market steward override. PDA [\"steward\", market_id].",
        "effective steward = this account if it exists, else registry.default_steward."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "steward",
            "type": "pubkey"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "PositionOwner",
      "docs": [
        "Ownership record for a minted position (the engine's token_id is opaque bytes)."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "token_id",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "ProtocolState",
      "docs": [
        "Per-market protocol engine state: a postcard blob of livestreak_engine::Protocol.",
        "v1 mirrors Sui's registry-object shape (one state object per market) — the",
        "documented alternative to PDA-per-entity sharding; realloc grows it as needed."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market_id",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "bump",
            "type": "u8"
          },
          {
            "name": "data",
            "type": "bytes"
          }
        ]
      }
    },
    {
      "name": "Registry",
      "docs": [
        "Singleton protocol registry: market counter + steward default."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "market_count",
            "type": "u64"
          },
          {
            "name": "default_steward",
            "type": "pubkey"
          },
          {
            "name": "bump",
            "type": "u8"
          },
          {
            "name": "lvst_mint",
            "docs": [
              "Canonical LVST reward-token mint, recorded at the deployer-trusted `initialize`.",
              "Staking constrains the staked mint against this so a fake-mint stake can't later",
              "extract real USDC dividends. Placed LAST so market_count/default_steward/bump keep",
              "their byte offsets (wire.ts decodes default_steward at 16..48); InitSpace adds 32."
            ],
            "type": "pubkey"
          }
        ]
      }
    }
  ]
} as const;

export type { Livestreak } from "./livestreak-types.js";
export type LivestreakIdl = Livestreak;
