// Auto-generated by anchor build (synced by sync-idl.mjs) — do not edit by hand.
/**
 * Program IDL in camelCase format in order to be used in JS/TS.
 *
 * Note that this is only a type helper and is not the actual IDL. The original
 * IDL can be found at `target/idl/livestreak.json`.
 */
export type Livestreak = {
  "address": "CZnAfgbnbVtuXDRQynwL9XMHqeQ7wngbodRihGLbErK8",
  "metadata": {
    "name": "livestreak",
    "version": "0.1.0",
    "spec": "0.1.0",
    "description": "LiveStreak protocol — Solana port (ported from the Sui Move sources)"
  },
  "instructions": [
    {
      "name": "advance",
      "discriminator": [
        7,
        56,
        108,
        201,
        36,
        20,
        57,
        89
      ],
      "accounts": [
        {
          "name": "protocolState",
          "writable": true
        },
        {
          "name": "escrow",
          "docs": [
            "Read-only: present so the conservation guard can verify the invariant."
          ]
        }
      ],
      "args": [
        {
          "name": "vaultId",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        },
        {
          "name": "side",
          "type": "u8"
        },
        {
          "name": "maxSteps",
          "type": "u64"
        }
      ]
    },
    {
      "name": "claimDividends",
      "discriminator": [
        105,
        60,
        172,
        2,
        136,
        93,
        128,
        151
      ],
      "accounts": [
        {
          "name": "staker",
          "signer": true
        },
        {
          "name": "protocolState",
          "writable": true
        },
        {
          "name": "escrow",
          "writable": true
        },
        {
          "name": "stakerUsdc",
          "docs": [
            "The staker's USDC token account. Require-exists (mirrors the other user_usdc ATAs)."
          ],
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": []
    },
    {
      "name": "claimLossLvst",
      "discriminator": [
        106,
        174,
        157,
        64,
        132,
        175,
        142,
        147
      ],
      "accounts": [
        {
          "name": "claimer",
          "signer": true
        },
        {
          "name": "protocolState",
          "writable": true
        },
        {
          "name": "position",
          "docs": [
            "Ownership gate: the claimer must own the position whose token_id fixes the loss."
          ]
        },
        {
          "name": "lvstAuthority",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  118,
                  115,
                  116,
                  95,
                  97,
                  117,
                  116,
                  104,
                  111,
                  114,
                  105,
                  116,
                  121
                ]
              }
            ]
          }
        },
        {
          "name": "lvstMint",
          "docs": [
            "The canonical LVST mint (its authority must be the lvst_authority PDA)."
          ],
          "writable": true
        },
        {
          "name": "claimerLvst",
          "docs": [
            "The claimer's LVST token account. Require-exists (mirrors how the program treats",
            "user USDC ATAs): the client prepends a createAtaIdempotent for the LVST mint."
          ],
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "vaultId",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        },
        {
          "name": "side",
          "type": "u8"
        }
      ]
    },
    {
      "name": "collect",
      "discriminator": [
        208,
        47,
        194,
        155,
        17,
        98,
        82,
        236
      ],
      "accounts": [
        {
          "name": "protocolState",
          "writable": true
        },
        {
          "name": "escrow",
          "docs": [
            "Read-only: present so the conservation guard can verify the invariant."
          ]
        }
      ],
      "args": [
        {
          "name": "vaultId",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "createVaultSeeded",
      "discriminator": [
        203,
        113,
        87,
        226,
        69,
        108,
        101,
        19
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "protocolState",
          "writable": true
        },
        {
          "name": "escrow",
          "writable": true
        },
        {
          "name": "userUsdc",
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "question",
          "type": "bytes"
        },
        {
          "name": "seedSide",
          "type": "u8"
        },
        {
          "name": "rate",
          "type": "u64"
        },
        {
          "name": "deposit",
          "type": "u64"
        }
      ],
      "returns": "bytes"
    },
    {
      "name": "fund",
      "discriminator": [
        218,
        188,
        111,
        221,
        152,
        113,
        174,
        7
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "protocolState",
          "writable": true
        },
        {
          "name": "position"
        },
        {
          "name": "escrow",
          "writable": true
        },
        {
          "name": "userUsdc",
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "vaultId",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        },
        {
          "name": "side",
          "type": "u8"
        },
        {
          "name": "rate",
          "type": "u64"
        },
        {
          "name": "deposit",
          "type": "u64"
        }
      ]
    },
    {
      "name": "goLive",
      "discriminator": [
        126,
        98,
        10,
        43,
        92,
        184,
        85,
        248
      ],
      "accounts": [
        {
          "name": "creator",
          "signer": true,
          "relations": [
            "market"
          ]
        },
        {
          "name": "market",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "scheme",
          "type": "u8"
        },
        {
          "name": "pointer",
          "type": "bytes"
        }
      ]
    },
    {
      "name": "growProtocol",
      "discriminator": [
        12,
        163,
        83,
        216,
        176,
        210,
        100,
        45
      ],
      "accounts": [
        {
          "name": "payer",
          "writable": true,
          "signer": true
        },
        {
          "name": "protocolState",
          "writable": true
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": []
    },
    {
      "name": "initProtocol",
      "discriminator": [
        3,
        188,
        141,
        237,
        225,
        226,
        232,
        210
      ],
      "accounts": [
        {
          "name": "payer",
          "writable": true,
          "signer": true
        },
        {
          "name": "market"
        },
        {
          "name": "protocolState",
          "writable": true
        },
        {
          "name": "usdcMint"
        },
        {
          "name": "escrow",
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "capacity",
          "type": "u16"
        }
      ]
    },
    {
      "name": "initialize",
      "discriminator": [
        175,
        175,
        109,
        31,
        13,
        152,
        155,
        237
      ],
      "accounts": [
        {
          "name": "payer",
          "writable": true,
          "signer": true
        },
        {
          "name": "registry",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  101,
                  103,
                  105,
                  115,
                  116,
                  114,
                  121
                ]
              }
            ]
          }
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "defaultSteward",
          "type": "pubkey"
        },
        {
          "name": "lvstMint",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "mintPosition",
      "discriminator": [
        251,
        31,
        179,
        3,
        138,
        134,
        203,
        28
      ],
      "accounts": [
        {
          "name": "payer",
          "writable": true,
          "signer": true
        },
        {
          "name": "minter",
          "signer": true
        },
        {
          "name": "protocolState",
          "writable": true
        },
        {
          "name": "market"
        },
        {
          "name": "position",
          "writable": true
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "salt",
          "type": "u64"
        }
      ]
    },
    {
      "name": "registerMarket",
      "discriminator": [
        24,
        163,
        183,
        185,
        145,
        243,
        36,
        146
      ],
      "accounts": [
        {
          "name": "creator",
          "writable": true,
          "signer": true
        },
        {
          "name": "registry",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  101,
                  103,
                  105,
                  115,
                  116,
                  114,
                  121
                ]
              }
            ]
          }
        },
        {
          "name": "market",
          "writable": true
        },
        {
          "name": "marketIndex",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  109,
                  97,
                  114,
                  107,
                  101,
                  116,
                  95,
                  105,
                  100,
                  120
                ]
              },
              {
                "kind": "account",
                "path": "registry.marketCount",
                "account": "registry"
              }
            ]
          }
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "title",
          "type": "bytes"
        },
        {
          "name": "streamId",
          "type": "bytes"
        }
      ]
    },
    {
      "name": "resolve",
      "discriminator": [
        246,
        150,
        236,
        206,
        108,
        63,
        58,
        10
      ],
      "accounts": [
        {
          "name": "steward",
          "signer": true
        },
        {
          "name": "protocolState",
          "writable": true
        },
        {
          "name": "registry",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  101,
                  103,
                  105,
                  115,
                  116,
                  114,
                  121
                ]
              }
            ]
          }
        },
        {
          "name": "marketSteward",
          "docs": [
            "Per-market override; pass the registry's default when none exists."
          ],
          "optional": true
        }
      ],
      "args": [
        {
          "name": "vaultId",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        },
        {
          "name": "winningSide",
          "type": "u8"
        }
      ]
    },
    {
      "name": "setDefaultSteward",
      "discriminator": [
        147,
        90,
        32,
        234,
        146,
        51,
        12,
        85
      ],
      "accounts": [
        {
          "name": "authority",
          "signer": true
        },
        {
          "name": "registry",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  101,
                  103,
                  105,
                  115,
                  116,
                  114,
                  121
                ]
              }
            ]
          }
        }
      ],
      "args": [
        {
          "name": "steward",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "setEnded",
      "discriminator": [
        138,
        92,
        84,
        48,
        74,
        233,
        182,
        216
      ],
      "accounts": [
        {
          "name": "creator",
          "signer": true,
          "relations": [
            "market"
          ]
        },
        {
          "name": "market",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "scheme",
          "type": "u8"
        },
        {
          "name": "pointer",
          "type": "bytes"
        }
      ]
    },
    {
      "name": "setLanes",
      "discriminator": [
        199,
        5,
        232,
        61,
        20,
        92,
        40,
        134
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "protocolState",
          "writable": true
        },
        {
          "name": "position"
        },
        {
          "name": "escrow",
          "writable": true
        },
        {
          "name": "userUsdc",
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "lanes",
          "type": {
            "vec": {
              "defined": {
                "name": "laneArg"
              }
            }
          }
        },
        {
          "name": "addDeposit",
          "type": "u64"
        }
      ]
    },
    {
      "name": "setMarketSteward",
      "discriminator": [
        124,
        136,
        234,
        202,
        9,
        248,
        242,
        31
      ],
      "accounts": [
        {
          "name": "authority",
          "writable": true,
          "signer": true
        },
        {
          "name": "registry",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  101,
                  103,
                  105,
                  115,
                  116,
                  114,
                  121
                ]
              }
            ]
          }
        },
        {
          "name": "market"
        },
        {
          "name": "marketSteward",
          "writable": true
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "steward",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "stakeLvst",
      "discriminator": [
        129,
        163,
        230,
        235,
        42,
        158,
        89,
        219
      ],
      "accounts": [
        {
          "name": "staker",
          "writable": true,
          "signer": true
        },
        {
          "name": "protocolState",
          "writable": true
        },
        {
          "name": "registry",
          "docs": [
            "Read-only registry: the canonical LVST mint lives here (recorded at initialize)."
          ],
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  101,
                  103,
                  105,
                  115,
                  116,
                  114,
                  121
                ]
              }
            ]
          }
        },
        {
          "name": "lvstMint"
        },
        {
          "name": "lvstEscrow",
          "docs": [
            "Per-market LVST staking escrow, created lazily on the first stake (payer = staker).",
            "init_if_needed is already an enabled anchor feature; a lazy init keeps this to the",
            "scoped two instructions (no separate init op / extra client round-trip) and cannot",
            "be griefed into a bad state — the seeds are fixed and the mint/authority constraints",
            "are re-checked on every call, so there is no trusted data to corrupt."
          ],
          "writable": true
        },
        {
          "name": "stakerLvst",
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "stopAll",
      "discriminator": [
        192,
        239,
        176,
        82,
        185,
        47,
        125,
        214
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "protocolState",
          "writable": true
        },
        {
          "name": "position"
        },
        {
          "name": "escrow",
          "writable": true
        },
        {
          "name": "userUsdc",
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": []
    },
    {
      "name": "stopFunding",
      "discriminator": [
        67,
        127,
        232,
        106,
        65,
        131,
        19,
        218
      ],
      "accounts": [
        {
          "name": "user",
          "signer": true
        },
        {
          "name": "protocolState",
          "writable": true
        },
        {
          "name": "position"
        }
      ],
      "args": [
        {
          "name": "vaultId",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        },
        {
          "name": "side",
          "type": "u8"
        }
      ]
    },
    {
      "name": "stopSeed",
      "discriminator": [
        194,
        156,
        255,
        171,
        197,
        193,
        16,
        245
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "protocolState",
          "writable": true
        },
        {
          "name": "escrow",
          "writable": true
        },
        {
          "name": "userUsdc",
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "vaultId",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "transferPosition",
      "discriminator": [
        139,
        130,
        102,
        147,
        135,
        77,
        113,
        222
      ],
      "accounts": [
        {
          "name": "owner",
          "signer": true
        },
        {
          "name": "position",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "newOwner",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "unstakeLvst",
      "discriminator": [
        145,
        44,
        251,
        143,
        99,
        253,
        94,
        26
      ],
      "accounts": [
        {
          "name": "staker",
          "signer": true
        },
        {
          "name": "protocolState",
          "writable": true
        },
        {
          "name": "lvstMint"
        },
        {
          "name": "lvstEscrow",
          "docs": [
            "Require-exists: you cannot unstake without a prior stake, which created this escrow."
          ],
          "writable": true
        },
        {
          "name": "stakerLvst",
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "withdraw",
      "discriminator": [
        183,
        18,
        70,
        156,
        148,
        109,
        161,
        34
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "protocolState",
          "writable": true
        },
        {
          "name": "position"
        },
        {
          "name": "escrow",
          "writable": true
        },
        {
          "name": "userUsdc",
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "vaultId",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "withdrawSeed",
      "discriminator": [
        6,
        229,
        202,
        82,
        245,
        58,
        212,
        125
      ],
      "accounts": [
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "protocolState",
          "writable": true
        },
        {
          "name": "escrow",
          "writable": true
        },
        {
          "name": "userUsdc",
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "vaultId",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    }
  ],
  "accounts": [
    {
      "name": "market",
      "discriminator": [
        219,
        190,
        213,
        55,
        0,
        227,
        198,
        154
      ]
    },
    {
      "name": "marketIndex",
      "discriminator": [
        82,
        184,
        235,
        96,
        200,
        193,
        242,
        21
      ]
    },
    {
      "name": "marketSteward",
      "discriminator": [
        183,
        148,
        185,
        192,
        99,
        97,
        65,
        169
      ]
    },
    {
      "name": "positionOwner",
      "discriminator": [
        178,
        102,
        135,
        78,
        61,
        157,
        171,
        203
      ]
    },
    {
      "name": "protocolState",
      "discriminator": [
        33,
        51,
        173,
        134,
        35,
        140,
        195,
        248
      ]
    },
    {
      "name": "registry",
      "discriminator": [
        47,
        174,
        110,
        246,
        184,
        182,
        252,
        218
      ]
    }
  ],
  "errors": [
    {
      "code": 6000,
      "name": "emptyTitle",
      "msg": "title must be non-empty"
    },
    {
      "code": 6001,
      "name": "zeroStreamId",
      "msg": "stream id must be non-empty"
    },
    {
      "code": 6002,
      "name": "inputTooLong",
      "msg": "input exceeds maximum length"
    },
    {
      "code": 6003,
      "name": "notCreator",
      "msg": "caller is not the market creator"
    },
    {
      "code": 6004,
      "name": "streamEnded",
      "msg": "stream already ended"
    },
    {
      "code": 6005,
      "name": "notLive",
      "msg": "stream was never live"
    },
    {
      "code": 6006,
      "name": "streamLocked",
      "msg": "stream pointer is locked (evidence grace elapsed)"
    },
    {
      "code": 6007,
      "name": "badScheme",
      "msg": "unknown storage pointer scheme"
    },
    {
      "code": 6008,
      "name": "engineState",
      "msg": "protocol state failed to decode"
    },
    {
      "code": 6009,
      "name": "stateFull",
      "msg": "protocol state account is full"
    },
    {
      "code": 6010,
      "name": "stateAtCapacity",
      "msg": "protocol state is at its maximum size; cannot grow further"
    },
    {
      "code": 6011,
      "name": "engineOp",
      "msg": "engine operation failed (see logs)"
    },
    {
      "code": 6012,
      "name": "notSteward",
      "msg": "caller is not the effective steward"
    },
    {
      "code": 6013,
      "name": "conservationViolated",
      "msg": "escrow balance diverged from engine ledgers"
    },
    {
      "code": 6014,
      "name": "settlementPending",
      "msg": "settlement pending: winnings payable after the cycle boundary at ready_at"
    },
    {
      "code": 6015,
      "name": "wrongLvstMint",
      "msg": "staked mint is not the canonical LVST mint recorded in the registry"
    },
    {
      "code": 6016,
      "name": "noDividends",
      "msg": "no dividends accrued to claim"
    },
    {
      "code": 6017,
      "name": "zeroNewOwner",
      "msg": "new position owner must be non-zero"
    },
    {
      "code": 6018,
      "name": "streamsTooManyReceivers",
      "msg": "too many stream receivers"
    },
    {
      "code": 6019,
      "name": "streamsReceiversNotSorted",
      "msg": "stream receivers not sorted"
    },
    {
      "code": 6020,
      "name": "streamsAmtPerSecTooLow",
      "msg": "stream rate below minimum"
    },
    {
      "code": 6021,
      "name": "streamsCycleSecsTooLow",
      "msg": "cycle seconds below minimum"
    },
    {
      "code": 6022,
      "name": "streamsInvalidReceivers",
      "msg": "invalid streams receivers"
    },
    {
      "code": 6023,
      "name": "streamsInvalidHistory",
      "msg": "invalid streams history"
    },
    {
      "code": 6024,
      "name": "streamsEntryWithHashAndReceivers",
      "msg": "history entry has both hash and receivers"
    },
    {
      "code": 6025,
      "name": "streamsTimestampBeforeUpdate",
      "msg": "timestamp before last update"
    },
    {
      "code": 6026,
      "name": "streamsBalanceTooHigh",
      "msg": "streams balance too high"
    },
    {
      "code": 6027,
      "name": "vaultEmptyQuestion",
      "msg": "vault question must be non-empty"
    },
    {
      "code": 6028,
      "name": "vaultZeroCreator",
      "msg": "vault creator must be non-zero"
    },
    {
      "code": 6029,
      "name": "vaultUnknown",
      "msg": "unknown vault"
    },
    {
      "code": 6030,
      "name": "vaultNotOpen",
      "msg": "vault is not open"
    },
    {
      "code": 6031,
      "name": "vaultZeroRate",
      "msg": "vault rate must be non-zero"
    },
    {
      "code": 6032,
      "name": "vaultAlreadyFunding",
      "msg": "position already funding this vault"
    },
    {
      "code": 6033,
      "name": "vaultLengthMismatch",
      "msg": "vault input length mismatch"
    },
    {
      "code": 6034,
      "name": "vaultNotResolvable",
      "msg": "vault is not resolvable"
    },
    {
      "code": 6035,
      "name": "vaultNotResolved",
      "msg": "vault is not resolved"
    },
    {
      "code": 6036,
      "name": "vaultBoardBehind",
      "msg": "board is behind; advance before settling"
    },
    {
      "code": 6037,
      "name": "vaultDivZero",
      "msg": "division by zero in vault math"
    },
    {
      "code": 6038,
      "name": "vaultInsufficientUsdc",
      "msg": "insufficient USDC in vault ledger"
    },
    {
      "code": 6039,
      "name": "driverSaltUsed",
      "msg": "mint salt already used"
    },
    {
      "code": 6040,
      "name": "driverUnknownMarket",
      "msg": "unknown market"
    },
    {
      "code": 6041,
      "name": "driverZeroRate",
      "msg": "lane rate must be non-zero"
    },
    {
      "code": 6042,
      "name": "driverBadDeposit",
      "msg": "bad deposit amount"
    },
    {
      "code": 6043,
      "name": "driverWrongMarket",
      "msg": "vault belongs to a different market"
    },
    {
      "code": 6044,
      "name": "driverVaultHasLane",
      "msg": "position already has a lane on this vault"
    },
    {
      "code": 6045,
      "name": "driverTooManyLanes",
      "msg": "too many lanes on this position"
    },
    {
      "code": 6046,
      "name": "driverNoLane",
      "msg": "no lane on this vault"
    },
    {
      "code": 6047,
      "name": "driverDuplicateVault",
      "msg": "duplicate vault in lane set"
    },
    {
      "code": 6048,
      "name": "driverLengthMismatch",
      "msg": "driver input length mismatch"
    },
    {
      "code": 6049,
      "name": "driverSeedExists",
      "msg": "seed lane already exists"
    },
    {
      "code": 6050,
      "name": "driverNoSeed",
      "msg": "no seed lane"
    },
    {
      "code": 6051,
      "name": "dripsTotalBalanceTooHigh",
      "msg": "total streamed balance too high"
    },
    {
      "code": 6052,
      "name": "dripsTokenBalanceTooLow",
      "msg": "token balance too low"
    },
    {
      "code": 6053,
      "name": "dripsWithdrawalAmountTooHigh",
      "msg": "withdrawal amount too high"
    },
    {
      "code": 6054,
      "name": "treasuryAlreadyClaimed",
      "msg": "loss already claimed"
    },
    {
      "code": 6055,
      "name": "treasuryNothingLost",
      "msg": "nothing lost to claim"
    },
    {
      "code": 6056,
      "name": "treasuryZeroStake",
      "msg": "stake must be non-zero"
    },
    {
      "code": 6057,
      "name": "treasuryInvalidUnstake",
      "msg": "invalid unstake amount"
    }
  ],
  "types": [
    {
      "name": "laneArg",
      "docs": [
        "One desired lane in a `set_lanes` full-set declaration. Rates are the human u64 the",
        "client speaks (mirroring `fund`); the handler widens each to the engine's U256 before",
        "the driver call. Anchor-(de)serializable so it rides in the `Vec<LaneArg>` arg."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "vaultId",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "side",
            "type": "u8"
          },
          {
            "name": "rate",
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "market",
      "docs": [
        "One market. PDA: [\"market\", market_id]. market_id = keccak256(creator ++ stream_id),",
        "the same id scheme as Move compute_market_id — 32 opaque bytes on every chain."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "marketId",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "creator",
            "type": "pubkey"
          },
          {
            "name": "title",
            "type": "bytes"
          },
          {
            "name": "streamId",
            "type": "bytes"
          },
          {
            "name": "createdAt",
            "type": "i64"
          },
          {
            "name": "streamStatus",
            "type": "u8"
          },
          {
            "name": "streamScheme",
            "type": "u8"
          },
          {
            "name": "streamPointer",
            "type": "bytes"
          },
          {
            "name": "streamUpdatedAt",
            "type": "i64"
          },
          {
            "name": "streamEndedAt",
            "type": "i64"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "marketIndex",
      "docs": [
        "Enumeration ledger: PDA [\"market_idx\", index_le] -> market_id.",
        "The append-only equivalent of EVM marketIdAt / Move market_ids."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "marketId",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "marketSteward",
      "docs": [
        "Per-market steward override. PDA [\"steward\", market_id].",
        "effective steward = this account if it exists, else registry.default_steward."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "steward",
            "type": "pubkey"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "positionOwner",
      "docs": [
        "Ownership record for a minted position (the engine's token_id is opaque bytes)."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "tokenId",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "marketId",
            "docs": [
              "The market this position was minted for. The per-token market accessor EVM",
              "(MarketDriver.marketIdOf) and Sui (the NFT's market_id field) already expose —",
              "lets a reader attribute a still-laneless position to its market instead of",
              "falling back to the zero id. Placed AFTER `owner` so owner keeps offset 40 and",
              "listOwnerTokens' memcmp filter is unchanged; market_id decodes at offset 72."
            ],
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "protocolState",
      "docs": [
        "Per-market protocol engine state: a postcard blob of livestreak_engine::Protocol.",
        "v1 mirrors Sui's registry-object shape (one state object per market) — the",
        "documented alternative to PDA-per-entity sharding; realloc grows it as needed."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "marketId",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "bump",
            "type": "u8"
          },
          {
            "name": "data",
            "type": "bytes"
          }
        ]
      }
    },
    {
      "name": "registry",
      "docs": [
        "Singleton protocol registry: market counter + steward default."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "marketCount",
            "type": "u64"
          },
          {
            "name": "defaultSteward",
            "type": "pubkey"
          },
          {
            "name": "bump",
            "type": "u8"
          },
          {
            "name": "lvstMint",
            "docs": [
              "Canonical LVST reward-token mint, recorded at the deployer-trusted `initialize`.",
              "Staking constrains the staked mint against this so a fake-mint stake can't later",
              "extract real USDC dividends. Placed LAST so market_count/default_steward/bump keep",
              "their byte offsets (wire.ts decodes default_steward at 16..48); InitSpace adds 32."
            ],
            "type": "pubkey"
          }
        ]
      }
    }
  ]
};
