/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RemoteTestRouteImport } from './routes/remote-test'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StreamIdRouteImport } from './routes/stream/$id'
import { Route as RemoteSessionRouteImport } from './routes/remote/$session'

const RemoteTestRoute = RemoteTestRouteImport.update({
  id: '/remote-test',
  path: '/remote-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamIdRoute = StreamIdRouteImport.update({
  id: '/stream/$id',
  path: '/stream/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteSessionRoute = RemoteSessionRouteImport.update({
  id: '/remote/$session',
  path: '/remote/$session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/remote-test': typeof RemoteTestRoute
  '/remote/$session': typeof RemoteSessionRoute
  '/stream/$id': typeof StreamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/remote-test': typeof RemoteTestRoute
  '/remote/$session': typeof RemoteSessionRoute
  '/stream/$id': typeof StreamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/remote-test': typeof RemoteTestRoute
  '/remote/$session': typeof RemoteSessionRoute
  '/stream/$id': typeof StreamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/remote-test'
    | '/remote/$session'
    | '/stream/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agents' | '/remote-test' | '/remote/$session' | '/stream/$id'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/remote-test'
    | '/remote/$session'
    | '/stream/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  RemoteTestRoute: typeof RemoteTestRoute
  RemoteSessionRoute: typeof RemoteSessionRoute
  StreamIdRoute: typeof StreamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/remote-test': {
      id: '/remote-test'
      path: '/remote-test'
      fullPath: '/remote-test'
      preLoaderRoute: typeof RemoteTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/$id': {
      id: '/stream/$id'
      path: '/stream/$id'
      fullPath: '/stream/$id'
      preLoaderRoute: typeof StreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote/$session': {
      id: '/remote/$session'
      path: '/remote/$session'
      fullPath: '/remote/$session'
      preLoaderRoute: typeof RemoteSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  RemoteTestRoute: RemoteTestRoute,
  RemoteSessionRoute: RemoteSessionRoute,
  StreamIdRoute: StreamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
