// Copies the anchor-generated IDL + TS types from program/target into the committed
// chains/solana/idl/ surface (the wagmi-generated-ABIs analog). Run after `anchor build`.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const solanaRoot = join(here, "..");
const target = join(solanaRoot, "program", "target");
const outDir = join(solanaRoot, "idl");
mkdirSync(outDir, { recursive: true });

const idl = readFileSync(join(target, "idl", "livestreak.json"), "utf8");
writeFileSync(join(outDir, "livestreak.json"), idl);

const types = readFileSync(join(target, "types", "livestreak.ts"), "utf8");
writeFileSync(
  join(outDir, "livestreak-types.ts"),
  `// Auto-generated by anchor build (synced by sync-idl.mjs) — do not edit by hand.\n${types}`,
);

const indexTs = [
  "// Auto-generated by sync-idl.mjs from program/target/idl — do not edit by hand.",
  "// Re-run `npm run build:solana:idl` after `anchor build` to refresh.",
  'import type { Livestreak } from "./livestreak-types.js";',
  "",
  `export const livestreakIdl = ${idl.trim()} as const;`,
  "",
  'export type { Livestreak } from "./livestreak-types.js";',
  "export type LivestreakIdl = Livestreak;",
  "",
].join("\n");
writeFileSync(join(outDir, "index.ts"), indexTs);

console.log("synced IDL + types into chains/solana/idl/");
