// Auto-generated by deploy — do not edit by hand.
// Re-run promote after deploy to regenerate from the latest localhost snapshot.
import type { EvmDeployOutput } from "../types.js";

export const localhostDeployment: EvmDeployOutput = {
  chain: "localhost",
  chainId: 31337,
  rpc: "http://127.0.0.1:8545",
  deployedAt: "2026-06-17T09:54:01.869Z",
  deployer: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
  scopes: {
    "aa": {
      "status": "completed",
      "deployedAt": "2026-06-30T20:28:29.637Z",
      "contracts": {
        "entryPoint": "0x0000000071727De22E5E9d8BAf0edAc6f37da032",
        "safeSingleton": "0x31ea225b4289bcf8d16764b86af6a699faa31c45",
        "safeProxyFactory": "0x8e5df391a248073b244270bdb99599abe51834d6",
        "safeModuleSetup": "0x71ebd4303657bf41f4b730f06536fd5b580dbdca",
        "safe4337Module": "0x7240e794b12f848dea622a0da206d1b7d71d56bd",
        "multiSend": "0x0a1e9f157d53f156a4dc0479fa2af500ba7d5f87",
        "multiSendCallOnly": "0x90fe1a52c5e6d204e1ec36c48dbe79cbc209d3aa",
        "fallbackHandler": "0x9dbfb7147d46e23d6db4ebedd41c22005d376a0b",
        "signMessageLib": "0x030dcedf7dcb4238db145e4bc3d8707c90c317eb",
        "createCall": "0x9c25750c3f274facf6eeec33d5d1e0bf9b6a3da3",
        "simulateTxAccessor": "0x06041007e4f2e33aa5c42f4cb2a062bb8dbd398c"
      }
    },
    "streaming": {
      "status": "completed",
      "deployedAt": "2026-06-30T20:28:29.638Z",
      "contracts": {
        "dripsStreaming": "0xc20641edde8cecf5a6530a3edbd7fbbffe0bf3d5",
        "dripsProxy": "0xbf1f98e88faecf0fb3c8bea93cbdfbeef4aa57d4",
        "caller": "0x69af9aa0e3ba6530d2f947a6e9c61f5691e8a72b"
      }
    },
    "protocol": {
      "status": "completed",
      "deployedAt": "2026-06-30T20:28:29.716Z",
      "contracts": {
        "protocol": "0xfe7b1de3c0b7a330b04d854c91fb762886aeb69e",
        "marketRegistry": "0x24599b53386dbe94dc7acb48dd5815ff51416683",
        "vault": "0x0a4ccf1ab21ff093d82c92b23f9cb3060dece377",
        "mockUsdc": "0x76bb00aa1936dd7cda6df2fa403f1439e3db456a",
        "lvstToken": "0x25db7a4a2aadbdd1c0045006a5df4eaa8f2ce46b",
        "treasury": "0xf9ebbc137fe61723bbe644dfc5dca8eea568bbb5",
        "stewardRegistry": "0xef7431bfb8a65e04ab3244c72cd7bdc55196dd4a"
      }
    },
    "wire": {
      "status": "completed",
      "deployedAt": "2026-06-30T20:28:29.804Z",
      "contracts": {
        "vaultDriver": "0x981a0340610d6ccc666911bbd3bf291c0e13919e",
        "marketDriverLogic": "0x955825800bdf781f29db41b7b438d3162632a151",
        "marketDriverProxy": "0x1db2e16805d28057d298d794591f8a620a3a1c1d"
      }
    },
    "paymaster": {
      "status": "completed",
      "deployedAt": "2026-06-30T20:28:29.821Z",
      "contracts": {
        "verifyingPaymaster": "0x547f60b6c453178c851d529bf36e9bccc57ba844",
        "verifyingSigner": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
      }
    }
  },
};
