// B1 bundler-seam proof (node path): the app can import the @livestreak/contracts
// solana barrel and the engine WASM actually loads + decodes. This exercises
// engine-wasm.ts's Node branch (initSync via readFile of the dist-copied .wasm),
// asserting byte-exact views against the contracts round-trip fixture. The browser
// path (new URL(..., import.meta.url)) is proved separately by
// scripts/verify-wasm-asset.mjs, which asserts vite emits the .wasm as a build asset.
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { expect, it } from 'vitest'
import { decodeProtocolBlob } from '@livestreak/contracts/solana'

// Fixture lives in the contracts package (generated by its gen-fixture example).
const fixturesDir = fileURLToPath(
  new URL('../../packages/contracts/chains/solana/test-fixtures/', import.meta.url),
)

it('loads the solana engine WASM and decodes a fixture blob byte-exact', async () => {
  const blob = readFileSync(fixturesDir + 'protocol-blob.bin')
  const expected = JSON.parse(readFileSync(fixturesDir + 'expected.json', 'utf8'))

  const view = await decodeProtocolBlob(blob)
  try {
    expect(view.listVaultIds()).toEqual([expected.vaultId])
    expect(view.marketVaults(expected.marketId)).toEqual([expected.vaultId])
    expect(view.pot(expected.vaultId)).toBe(BigInt(expected.pot))
    expect(view.board(expected.vaultId, 0).sideRate).toBe(BigInt(expected.boardYes.sideRate))
    expect(view.pendingShares(expected.vaultId, 0, expected.tokenId, expected.now)).toBe(
      BigInt(expected.pendingSharesYes),
    )
    expect(view.summary().escrowExpected).toBe(BigInt(expected.escrowExpected))
  } finally {
    view.free()
  }
})
