// Auto-generated by deploy:solana — do not edit by hand.
// Re-run `npm run deploy:solana` to regenerate from the latest localnet deployment.
import type { SolanaDeployment } from "../types.js";

export const localnetDeployment: SolanaDeployment = {
  chain: "localnet",
  rpc: "http://127.0.0.1:8899",
  deployedAt: "2026-07-17T20:30:03.985Z",
  deployer: "5QgNMwSCV3fCLhgnxvNgeRnffCWjY7Hqbb1TCq6Jfw2U",
  programId: "CZnAfgbnbVtuXDRQynwL9XMHqeQ7wngbodRihGLbErK8",
  accounts: {
    usdcMint: "H3AJ7CxLvSMkrJG5H4bZDjh1m2oHbBAWjo82RUHJbTGN",
    registry: "GgDkEWEaxPGpqi8DkFuH6EVUTL7k9g2YL9wG2Ahj6PNv",
    defaultSteward: "5QgNMwSCV3fCLhgnxvNgeRnffCWjY7Hqbb1TCq6Jfw2U",
  },
};
